### ISSUE TITLE
gr-gsm-git

### ISSUE THREAD

**Issue by crblackw** [yuvadm/archlinux-packages#12]
Hi,

For gr-gsm-git, I am getting an upgrade notification every time I " yaourt -Syua".  The upgrade pulls the same version of the repo, reinstalls and prompts again on the next upgrade.

Looking at the PKGBUILD for gr-gsm-git it references a pkgver of "30f3945".  The latest commit on the gr-gsm-git repo is "a25b830".  I think the PKGBUILD should reference this pkgver.

Thanks for maintaining.

Chris

**Comment by crblackw** [comment]
Pull request submitted.

**Comment by yuvadm** [comment]
@crblackw `pkgver` for `-git` packages means nothing, if you `makepkg` from scratch you should get a clean build from `HEAD`.
